<?php
// Nutrition data
$nutrition_items = [
  // CHICKEN ENTREES
  [
    "id" => "orange-chicken",
    "name" => "Orange Chicken",
    "category" => "Chicken",
    "servingSizeOz" => 5.92,
    "calories" => 510,
    "caloriesFromFat" => 220,
    "totalFat" => 24,
    "saturatedFat" => 5,
    "transFat" => 0,
    "cholesterol" => 86,
    "sodium" => 850,
    "totalCarbs" => 53,
    "fiber" => 2,
    "sugars" => 20,
    "protein" => 26,
    "allergens" => ["wheat", "soy", "egg"]
  ],
  [
    "id" => "kung-pao-chicken",
    "name" => "Kung Pao Chicken",
    "category" => "Chicken",
    "servingSizeOz" => 6.3,
    "calories" => 320,
    "caloriesFromFat" => 190,
    "totalFat" => 21,
    "saturatedFat" => 3.5,
    "transFat" => 0,
    "cholesterol" => 65,
    "sodium" => 940,
    "totalCarbs" => 14,
    "fiber" => 2,
    "sugars" => 7,
    "protein" => 19,
    "allergens" => ["peanut", "wheat", "soy"]
  ],
  [
    "id" => "string-bean-chicken",
    "name" => "String Bean Chicken Breast",
    "category" => "Chicken",
    "servingSizeOz" => 6,
    "calories" => 210,
    "caloriesFromFat" => 90,
    "totalFat" => 10,
    "saturatedFat" => 2,
    "transFat" => 0,
    "cholesterol" => 50,
    "sodium" => 740,
    "totalCarbs" => 13,
    "fiber" => 4,
    "sugars" => 5,
    "protein" => 18,
    "allergens" => ["wheat", "soy"]
  ],
  [
    "id" => "grilled-teriyaki-chicken",
    "name" => "Grilled Teriyaki Chicken",
    "category" => "Chicken",
    "servingSizeOz" => 6,
    "calories" => 300,
    "caloriesFromFat" => 110,
    "totalFat" => 13,
    "saturatedFat" => 3,
    "transFat" => 0,
    "cholesterol" => 115,
    "sodium" => 530,
    "totalCarbs" => 15,
    "fiber" => 1,
    "sugars" => 9,
    "protein" => 36,
    "allergens" => ["wheat", "soy"]
  ],
  [
    "id" => "sweetfire-chicken",
    "name" => "SweetFire Chicken Breast",
    "category" => "Chicken",
    "servingSizeOz" => 5.8,
    "calories" => 380,
    "caloriesFromFat" => 140,
    "totalFat" => 16,
    "saturatedFat" => 3,
    "transFat" => 0,
    "cholesterol" => 80,
    "sodium" => 380,
    "totalCarbs" => 42,
    "fiber" => 1,
    "sugars" => 19,
    "protein" => 19,
    "allergens" => ["wheat", "soy"]
  ],

  // BEEF ENTREES
  [
    "id" => "broccoli-beef",
    "name" => "Broccoli Beef",
    "category" => "Beef",
    "servingSizeOz" => 5.4,
    "calories" => 150,
    "caloriesFromFat" => 60,
    "totalFat" => 7,
    "saturatedFat" => 2,
    "transFat" => 0,
    "cholesterol" => 30,
    "sodium" => 660,
    "totalCarbs" => 13,
    "fiber" => 2,
    "sugars" => 7,
    "protein" => 9,
    "allergens" => ["wheat", "soy"]
  ],
  [
    "id" => "beijing-beef",
    "name" => "Beijing Beef",
    "category" => "Beef",
    "servingSizeOz" => 5.6,
    "calories" => 480,
    "caloriesFromFat" => 240,
    "totalFat" => 26,
    "saturatedFat" => 5,
    "transFat" => 0,
    "cholesterol" => 50,
    "sodium" => 890,
    "totalCarbs" => 48,
    "fiber" => 3,
    "sugars" => 24,
    "protein" => 14,
    "allergens" => ["wheat", "soy"]
  ],
  [
    "id" => "black-pepper-angus-steak",
    "name" => "Black Pepper Angus Steak",
    "category" => "Beef",
    "servingSizeOz" => 5.9,
    "calories" => 180,
    "caloriesFromFat" => 60,
    "totalFat" => 7,
    "saturatedFat" => 2,
    "transFat" => 0,
    "cholesterol" => 40,
    "sodium" => 850,
    "totalCarbs" => 15,
    "fiber" => 2,
    "sugars" => 6,
    "protein" => 16,
    "allergens" => ["wheat", "soy"]
  ],

  // SEAFOOD ENTREES
  [
    "id" => "honey-walnut-shrimp",
    "name" => "Honey Walnut Shrimp",
    "category" => "Seafood",
    "servingSizeOz" => 3.7,
    "calories" => 510,
    "caloriesFromFat" => 290,
    "totalFat" => 32,
    "saturatedFat" => 6,
    "transFat" => 0,
    "cholesterol" => 115,
    "sodium" => 380,
    "totalCarbs" => 42,
    "fiber" => 3,
    "sugars" => 22,
    "protein" => 14,
    "allergens" => ["shellfish", "tree nut", "wheat", "egg"]
  ],

  // SIDES
  [
    "id" => "fried-rice",
    "name" => "Fried Rice",
    "category" => "Sides",
    "servingSizeOz" => 9.4,
    "calories" => 520,
    "caloriesFromFat" => 140,
    "totalFat" => 16,
    "saturatedFat" => 3,
    "transFat" => 0,
    "cholesterol" => 115,
    "sodium" => 820,
    "totalCarbs" => 80,
    "fiber" => 3,
    "sugars" => 4,
    "protein" => 12,
    "allergens" => ["wheat", "soy", "egg"]
  ],
  [
    "id" => "chow-mein",
    "name" => "Chow Mein",
    "category" => "Sides",
    "servingSizeOz" => 9.4,
    "calories" => 510,
    "caloriesFromFat" => 180,
    "totalFat" => 20,
    "saturatedFat" => 3.5,
    "transFat" => 0,
    "cholesterol" => 0,
    "sodium" => 980,
    "totalCarbs" => 72,
    "fiber" => 6,
    "sugars" => 9,
    "protein" => 12,
    "allergens" => ["wheat", "soy"]
  ],
  [
    "id" => "white-steamed-rice",
    "name" => "White Steamed Rice",
    "category" => "Sides",
    "servingSizeOz" => 8.1,
    "calories" => 380,
    "caloriesFromFat" => 0,
    "totalFat" => 0,
    "saturatedFat" => 0,
    "transFat" => 0,
    "cholesterol" => 0,
    "sodium" => 0,
    "totalCarbs" => 87,
    "fiber" => 0,
    "sugars" => 0,
    "protein" => 7,
    "allergens" => []
  ],
  [
    "id" => "super-greens",
    "name" => "Super Greens",
    "category" => "Sides",
    "servingSizeOz" => 7.6,
    "calories" => 90,
    "caloriesFromFat" => 25,
    "totalFat" => 3,
    "saturatedFat" => 0,
    "transFat" => 0,
    "cholesterol" => 0,
    "sodium" => 530,
    "totalCarbs" => 10,
    "fiber" => 5,
    "sugars" => 3,
    "protein" => 6,
    "allergens" => ["wheat"]
  ],

  // APPETIZERS
  [
    "id" => "chicken-egg-roll",
    "name" => "Chicken Egg Roll (1 roll)",
    "category" => "Appetizers",
    "servingSizeOz" => 3,
    "calories" => 200,
    "caloriesFromFat" => 90,
    "totalFat" => 10,
    "saturatedFat" => 2,
    "transFat" => 0,
    "cholesterol" => 20,
    "sodium" => 390,
    "totalCarbs" => 20,
    "fiber" => 2,
    "sugars" => 2,
    "protein" => 8,
    "allergens" => ["wheat", "soy", "egg"]
  ],
  [
    "id" => "veggie-spring-roll",
    "name" => "Veggie Spring Roll (2 rolls)",
    "category" => "Appetizers",
    "servingSizeOz" => 3.4,
    "calories" => 190,
    "caloriesFromFat" => 70,
    "totalFat" => 8,
    "saturatedFat" => 1.5,
    "transFat" => 0,
    "cholesterol" => 0,
    "sodium" => 520,
    "totalCarbs" => 26,
    "fiber" => 2,
    "sugars" => 2,
    "protein" => 4,
    "allergens" => ["wheat", "soy"]
  ],
  [
    "id" => "cream-cheese-rangoon",
    "name" => "Cream Cheese Rangoon (3 pieces)",
    "category" => "Appetizers",
    "servingSizeOz" => 2.4,
    "calories" => 190,
    "caloriesFromFat" => 70,
    "totalFat" => 8,
    "saturatedFat" => 5,
    "transFat" => 0,
    "cholesterol" => 35,
    "sodium" => 180,
    "totalCarbs" => 24,
    "fiber" => 2,
    "sugars" => 1,
    "protein" => 5,
    "allergens" => ["wheat", "milk", "soy"]
  ]
];
?>